class Autogenerated {
  String? name;
  String? age;
  String? professtion;
  Family? family;

  Autogenerated({this.name, this.age, this.professtion, this.family});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    age = json['age'];
    professtion = json['professtion'];
    family =
        json['family'] != null ? new Family.fromJson(json['family']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['age'] = this.age;
    data['professtion'] = this.professtion;
    if (this.family != null) {
      data['family'] = this.family!.toJson();
    }
    return data;
  }
}

class Family {
  String? father;
  String? mother;
  String? brother;

  Family({this.father, this.mother, this.brother});

  Family.fromJson(Map<String, dynamic> json) {
    father = json['father'];
    mother = json['mother'];
    brother = json['brother'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['father'] = this.father;
    data['mother'] = this.mother;
    data['brother'] = this.brother;
    return data;
  }
}
