import 'package:flutter/material.dart';
import 'package:fluttertest/dart/dartmodel.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List<Autogenerated> favrate =[
    
 Autogenerated(name: 'raj',age: '12',professtion: 'favrate',family: Family(father: "kahhaiya lal",mother: "durga devi",brother: "rak adn shubhma")),
 Autogenerated(name: 'surendra',age: '92',professtion: 'modle',family: Family(mother: 'mamta devi',brother: 'mahandra')),
 Autogenerated(name: 'surendra',age: '92',professtion: 'modle')

  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('data'),
      ),
      body: ListView.builder(itemCount: favrate.length,
        
        itemBuilder: (context, index) {
          if(favrate[index].family == null){print('null h re baba ${index}');}
          else{  return 
        
        ListTile(
          trailing: IconButton(onPressed: (){
            favrate.removeAt(index);
            setState(() {
              
            });
            }, icon: Icon(Icons.remove))
          ,
           subtitle: Text(favrate[index].professtion.toString()),
       
          leading: Text(favrate[index].age.toString()),
           title: 
           
           
           Text( favrate[index].family!.father.toString()),
       
        );}


      
      }),
    );
  }
}

